name: ehya
description: an app to revive abandoned Sunan

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  get_it: ^7.1.4
  flutter_svg: ^0.22.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/strings/

  fonts:
    - family: Arslan
      fonts:
        - asset: fonts/arslan_wessam.ttf
    - family: Tajawal
      fonts:
        - asset: fonts/tajawal_black.ttf
        - asset: fonts/tajawal_bold.ttf
        - asset: fonts/tajawal_extra_bold.ttf
        - asset: fonts/tajawal_extra_light.ttf
        - asset: fonts/tajawal_light.ttf
        - asset: fonts/tajawal_medium.ttf
        - asset: fonts/tajawal_regular.ttf
